---
- shell: "mkdir -p /mnt/disks/{{ item }}"
  become: true
  with_items:
    - "vol1"
    - "vol2"
    - "vol3"
    - "vol4"
    - "vol5"
  register: pvc_mnt

- name: assign docker permission to user
  become: true
  shell: "usermod -a -G docker {{ authconfig_sssd_user }}"
  ignore_errors: yes
